### ISSUE TITLE
textContent вместо append

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cinema#12]
https://github.com/Ktyby/Cinema/blob/343df9dae0418a8f6633f712de9ca73c4f7548f6/js/script.js#L26
тут лучше воспользоваться полем textContent у опшна, это менее затратно с точки зрения ресурсов (ну, логично, метод явно больше жрет, чем обычное поле)
https://developer.mozilla.org/ru/docs/Web/API/Node/textContent

**Comment by Ktyby** [comment]
done
