### ISSUE TITLE
сокращение кода

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cinema#16]
https://github.com/Ktyby/Cinema/blob/343df9dae0418a8f6633f712de9ca73c4f7548f6/js/script.js#L36-L41
вот эту вот большую конструкцию можно заменить на element.classList.toggle()
прочитать вот здесь: https://developer.mozilla.org/ru/docs/Web/API/Element/classList

**Comment by kirillgenets** [comment]
Хотя ладно, оставь как есть, неплохо. Но ссылочку все равно посети, там интересно)

**Comment by Morfey216** [comment]
Можно использовать тернарный оператор, это сильно сократит код

П.С. Прошу прощения, что вмешиваюсь )))

**Comment by Ktyby** [comment]
Done)
