### ISSUE TITLE
valueOfSelect === undefined: true

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cinema#3]
https://github.com/Ktyby/Cinema/blob/81c4bb6cfe29ad12bed5f09bb448fa81b0cd2030/js/script.js#L4-L34
Тудум. Вот и твоя проблема. let и const имеют блочную область видимости и в твоем случае на строчке 5, 9 и 14 абсолютно разные переменные valueOfSelect :)
А в строчке 14 у тебя оно вообще undefined, потому что ты его нигде не объявлял!

**Comment by Ktyby** [comment]
Почему в 14 строчке undfined? Как в 14 строке мне взять значение из, допустим, 9-ой?

**Comment by kirillgenets** [comment]
Прочитай про области видимости. Вот пример:
`
let a = 4;
if (a < 10) {
  let b = 3;
}

console.log(b);
`
Здесь консоль выведет undefined, потому что b объявлена в блоке кода (в нашем случае это if) и существует только там. Прочитай про блочную область видимости!!!
